on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: 'npm install'
      - run: 'npm run build'
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - uses: actions/setup-java@v1
      with:
        java-version: '8'
    - run: gem install s3_website
    - run: s3_website push
